# Generated by Django 3.1.3 on 2020-11-03 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('country', models.TextField(blank=True, max_length=100)),
                ('street', models.TextField(blank=True, max_length=100)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('website', models.TextField(blank=True, max_length=150, null=True, verbose_name='website')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_directory_path')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
