# Generated by Django 3.1.3 on 2020-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='daily_revenue',
            new_name='revenue',
        ),
        migrations.AddField(
            model_name='revenue',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
