# Generated by Django 3.1.3 on 2020-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
