# Generated by Django 3.1.3 on 2020-11-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_color'),
        ('articles', '0003_remove_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tags.tag', verbose_name='tag'),
        ),
    ]
